#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec  3 14:53:50 2022

@author: mcdowallsc
"""
''' ei38 needs bw2io==0.8.7 '''
""" need to run:1 pip install "eight==1.0.1" """


import bw2io as bi
import bw2data as bd

db_dir = "/home/mcdowallsc/data1/dbs/ei38/datasets/"

db_name = "cutoff38"
project = "cutoff38"



#%% IMPORT
#bd.projects.delete_project(project, delete_dir=True)

bd.projects.set_current(project)
bi.bw2setup()


db = bi.SingleOutputEcospold2Importer(db_dir, db_name, use_mp=False)
#db.apply_strategies()
#db.statistics()
#db.write_database()

